# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=30)),
                ('latitude', models.FloatField(null=True)),
                ('longtitude', models.FloatField(null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('last_update', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DroneHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmergencyCommon.Drone')),
            ],
        ),
        migrations.CreateModel(
            name='DroneMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, default=None, null=True)),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
                ('waypoint_longtitude', models.FloatField(blank=True, null=True)),
                ('waypoint_latitude', models.FloatField(blank=True, null=True)),
                ('goal_longtitude', models.FloatField(blank=True, default=None, null=True)),
                ('goal_latitude', models.FloatField(blank=True, default=None, null=True)),
                ('call_longtitude', models.FloatField(blank=True, default=None, null=True)),
                ('call_latitude', models.FloatField(blank=True, default=None, null=True)),
                ('accepted', models.NullBooleanField(default=None)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('the_drone', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EmergencyCommon.Drone')),
            ],
        ),
        migrations.CreateModel(
            name='DronePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('time', models.DateTimeField()),
                ('the_drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmergencyCommon.Drone')),
            ],
        ),
        migrations.AddField(
            model_name='drone',
            name='current_mission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EmergencyCommon.DroneMission'),
        ),
    ]
