# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyCommon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DronePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dronestate',
            name='drone',
        ),
        migrations.AddField(
            model_name='drone',
            name='eta',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='goal_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='goal_longtitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='longtitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='waypoint_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='waypoint_longtitude',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='DroneState',
        ),
        migrations.AddField(
            model_name='droneposition',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmergencyCommon.Drone'),
        ),
    ]
