# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyCommon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='dronemission',
            old_name='call_longtitude',
            new_name='call_longitude',
        ),
        migrations.RenameField(
            model_name='dronemission',
            old_name='goal_longtitude',
            new_name='goal_longitude',
        ),
        migrations.RenameField(
            model_name='dronemission',
            old_name='waypoint_longtitude',
            new_name='waypoint_longitude',
        ),
        migrations.RenameField(
            model_name='droneposition',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
