# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyCommon', '0004_drone_altitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='oes_altitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='oes_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='oes_longitude',
            field=models.FloatField(null=True),
        ),
    ]
